[package]
name = "shell_grunt2"
version = "0.1.0"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]

[dependencies]
libc = "0.2.22"
notify = "4.0.1"
term = "0.4.5"
time = "^0.1"
clap = "2.24.2"
lua = "0.0.10"
