[package]
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]
name = "shell_grunt2"
version = "0.1.0"

[dependencies]
clap = "2.24.2"
crossbeam = "0.2.10"
floating-duration = "0.1.1"
lazy_static = "0.2.8"
libc = "0.2.22"
lua = "0.0.10"
notify = "4.0.1"
regex = "0.2.1"
term = "0.4.5"
time = "^0.1"
